version: "3.3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - redis